sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t firstmyapp/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true firstmyapp/docker-react npm run test